//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoCloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pho_usuario_acesso
    {
        public int usa_id { get; set; }
        public int usa_fk_usuario { get; set; }
        public string usa_login { get; set; }
        public string usa_senha { get; set; }
        public string usa_email { get; set; }
        public System.DateTime usa_dataexpiracao { get; set; }
    
        public virtual pho_usuarios pho_usuarios { get; set; }
    }
}
