//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoCloud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pho_usuarios
    {
        public pho_usuarios()
        {
            this.pho_usuario_acesso = new HashSet<pho_usuario_acesso>();
        }
    
        public int usu_id { get; set; }
        public string usu_nome { get; set; }
        public string usu_sobrenome { get; set; }
        public int usu_nivel { get; set; }
        public string usu_diretoriobase { get; set; }
        public string usu_status { get; set; }
        public System.DateTime usu_datacadastro { get; set; }
    
        public virtual ICollection<pho_usuario_acesso> pho_usuario_acesso { get; set; }
    }
}
